### ISSUE TITLE
Adjust breakpoint for header

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-voiceofoc#12]
From about 768-930px wide, the new buttons overlap the VoOC logo:
<img width="767" alt="screen shot 2017-05-01 at 4 06 28 pm" src="https://cloud.githubusercontent.com/assets/1643734/25595260/bf70aa7a-2e89-11e7-90d8-427544f7d1f3.png">

I think we should change it to wrap and center, something like:
```
#header-donate-sidebar {
    position: relative;
    padding-top: 1.5em;
}
```
<img width="912" alt="screen shot 2017-05-01 at 4 21 23 pm" src="https://cloud.githubusercontent.com/assets/1643734/25595384/4000d188-2e8a-11e7-9e9d-536be7d9e2b8.png">

**Comment by julia-smith** [comment]
The new media query is being overwritten by the original styles for #header-donate-sidebar. The real problem is that mobile.less is being included too early in style.less. (Don't try to change that right now though – moving the include would affect too much.) Instead, please move the new media query out of mobile.less and into the bottom of style.less.

<img width="752" alt="screen shot 2017-05-08 at 3 16 44 pm" src="https://cloud.githubusercontent.com/assets/1643734/25823828/e9434bea-3402-11e7-9d86-7793e5fd97b6.png">
<img width="348" alt="screen shot 2017-05-08 at 3 23 24 pm" src="https://cloud.githubusercontent.com/assets/1643734/25823827/e9412ab8-3402-11e7-9fec-1725c6d9a2e4.png">

**Comment by rclachance** [comment]
#19 is deployed to staging
